Iridium-Development/IridiumSkyblock

- build.gradle.kts
This change will prevent dependency conflicts with other plugins which are using different versions of the same dependencies
> Start relocating all relevant dependencies

- plugin/src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
Potential fix of exception java.lang.IllegalArgumentException: y out of range (expected 0-255, got 256).
Full log: [https://pastebin.com/FyTqu8bP](https://pastebin.com/FyTqu8bP)
My fix ensures, that `maxy` is lower or equal to 255, by using `Math.min(...)` method.
Please test it before accepting.
> Potential fix of java.lang.IllegalArgumentException

- plugin/src/main/java/com/iridium/iridiumskyblock/listeners/EntityPickupItemListener.java
On old Minecraft versions like 1.8, the EntityItemPickupEvent does not exist. Therefore we have to use the PlayerItemPickupEvent instead which is, unfortunately, deprecated but should still work.
> Fix item pickup event for legacy versions

- src/main/java/com/iridium/iridiumskyblock/database/IslandReward.java
Raised column width default to 2048 to accomodate for more data. This data includes reward item lores and reward commands which can be added by a user through config. Therefore this limit can still be reached, but the user will have to change the limit in their database themself if they reach it.
closes #164
> Fix islandrewards not being saved on databases with a too small default column width

- src/main/java/com/iridium/iridiumskyblock/configs/Configuration.java
- src/main/java/com/iridium/iridiumskyblock/listeners/BucketListener.java
This is a useful feature for those absolute degenerates that dont know how to make a cobble gen, who doesnt know how to make a cobblegen in 2021? anyway lets not bully those bakas anymore.
It can be used to covert obsidian back into lava whenever they do mess up some how. I wrote this for 1.17 so it likely isnt that backwards compatible but whatever, Suck it old verisons
> Add Obsidian -> Lava Bucket

- build.gradle.kts
This will update these two dependencies and will switch back to the old dependency format because it's the only supported one for the new dependency manager of IntelliJ IDEA 2021.2
> Bump ormlite-jdbc & jetbrains-annotations, Chance dependency format

- src/main/java/com/iridium/iridiumskyblock/api/IslandCreateEvent.java
- src/main/java/com/iridium/iridiumskyblock/api/IslandDeleteEvent.java
- src/main/java/com/iridium/iridiumskyblock/api/IslandRegenEvent.java
- src/main/java/com/iridium/iridiumskyblock/api/UserChatToggleEvent.java
- src/main/java/com/iridium/iridiumskyblock/api/UserDemoteEvent.java
- src/main/java/com/iridium/iridiumskyblock/api/UserJoinEvent.java
- src/main/java/com/iridium/iridiumskyblock/api/UserKickEvent.java
- src/main/java/com/iridium/iridiumskyblock/api/UserLeaveEvent.java
- src/main/java/com/iridium/iridiumskyblock/api/UserPromoteEvent.java
- src/main/java/com/iridium/iridiumskyblock/commands/JoinCommand.java
I add missing and useful `UserJoinEvent` in the public API and made that calling in the `JoinCommand`.
Also the `UserLeaveEvent` has not a `@Getter` annotation above the class declaration, it also was fixed.
(sorry for any mistakes, it's my first PR here)
> Added UserJoinEvent and missing `@Getter` in some other events

- src/main/java/com/iridium/iridiumskyblock/commands/PrivateCommand.java
The plugin will no longer kick island members and send them back to spawn when the island is set to private
> Anti-Island Member Kick

- build.gradle.kts
- src/main/java/com/iridium/iridiumskyblock/commands/BiomeCommand.java
- src/main/java/com/iridium/iridiumskyblock/generators/OceanGenerator.java
- src/main/java/com/iridium/iridiumskyblock/gui/BiomeGUI.java
- src/main/java/com/iridium/iridiumskyblock/listeners/PlayerMoveListener.java
- src/main/java/com/iridium/iridiumskyblock/utils/LocationUtils.java
Since 1.17, Mojang has brought the new heights and Spigot has therefore, at the same time an API for it even if it is in datapack.
We can use it now!
> New Heights 1.17+

- src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
- src/main/java/com/iridium/iridiumskyblock/schematics/WorldEdit.java
Test on Windows 11 x64 : 
Java 16.0.1
Purpur 1.17.1 build 1400
WorldEdit 7.2.6 (No FAWE, No AWE)
I9-9900K (4 vcpu)
Without cache : 30 ms and 17 tps and 4 sec for teleport player
With cache :
- first paste : 30 ms / 17 tps / 4 sec for teleport player
- after : 10 ms / 20 tps and ~1 sec for teleport player
> Optimization: Cache WorldEdit schematic

- .github/ISSUE_TEMPLATE/bug_report.md
> Remove Ori from the issue template

- src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
- src/main/java/com/iridium/iridiumskyblock/api/IridiumSkyblockAPI.java
That method was added to support dependency injection, but since we're staying with singletons, this solution looks better in my opinion.
> Remove unnecessary API initialization method

- src/main/java/com/iridium/iridiumskyblock/bank/CrystalsBankItem.java
- src/main/java/com/iridium/iridiumskyblock/bank/ExperienceBankItem.java
- src/main/java/com/iridium/iridiumskyblock/bank/MoneyBankItem.java
- src/main/java/com/iridium/iridiumskyblock/configs/Messages.java
Actually tested this, no idea what's wrong with me
> Implement crystal depositing via Island bank

- src/main/java/com/iridium/iridiumskyblock/listeners/PlayerInteractListener.java
Disables the possibility to place the crystal item if it is set to a block, like player head.
> Fix Crystal Item Place

- src/main/java/com/iridium/iridiumskyblock/listeners/EntityExplodeListener.java
Fixes #584, TNT can still damage on islands where it hasn't been ignited at
> Fix explosions being able to happen on foreign islands

- src/main/java/com/iridium/iridiumskyblock/api/IslandDeleteEvent.java
- src/main/java/com/iridium/iridiumskyblock/commands/DeleteCommand.java
- src/main/java/com/iridium/iridiumskyblock/configs/Messages.java
I don't really like this solution, but I guess it's alright for now
> Add command to delete other islands

- src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
- src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
**How this works**
When you configure a mission, you can now set the slot to numbers other than 0. This will determine the weight of this mission. The selection is still random, but the missions that have been selected will be ordered according to their weight, starting with the lowest slot. This will allow users to prevent missions from switching slots when they don't want them to.
> Add weight to the mission slots

- src/main/java/com/iridium/iridiumskyblock/configs/Schematics.java
Ran the `/is home currentOffset` command for all 9 schematics. The issue is that they all have different offsets, I used the one from the overworld schematic. However, we should probably implement offsets for all three dimensions.
Here is the list I compiled (second one is nether, third one is end), in case we need it for further changes:
```
Desert 1.5 88 -0.5 90
- 0.5 91 0.5 180
- 2.5 88 0.5 90
Jungle 0.5 82 4.5 180
- 0.5 89 0.5 0
- 0.5 90 0.5 180
Mushroom 1.5 89 -0.5 90
- 0.5 91 0.5 180
- 0.5 91 -3.5 0
```
> Fix default schematic offsets

- src/main/java/com/iridium/iridiumskyblock/gui/VisitGUI.java
Hello! I found a problem with teleportation to islands when using gui /is visit with /is bypass enabled. The problem is that if /is bypass is enabled, it confuses the index of the pressed island and teleports to a completely different island. This PR will probably fix this problem (need to check)
> Fix is visit with isBypassing

- src/main/java/com/iridium/iridiumskyblock/commands/Command.java
> Fix command execution for subcommands in camelCase

- src/main/java/com/iridium/iridiumskyblock/placeholders/Placeholders.java
Fix top island placeholders by disabling the caching that happened during plugin load time and use the caching done by IslandManager.
> Fix top island placeholder

- src/main/java/com/iridium/iridiumskyblock/managers/SchematicManager.java
- src/main/java/com/iridium/iridiumskyblock/schematics/WorldEdit.java
Verify if WorldEdit is incompatible with the current Minecraft version and switch back to default integration with a warning if that is the case.
> WorldEdit incompatibility check

- build.gradle.kts
Changes List:
- Updated version of IridiumTeams to make IridiumSkybloc compatible with spigot 1.20.
> Updated IridiumTeams version

- build.gradle.kts
- src/main/java/com/iridium/iridiumskyblock/commands/RegenCommand.java
- src/main/java/com/iridium/iridiumskyblock/configs/Configuration.java
- src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
Added the config options clearInventoryOnRegen & clearEnderChestOnRegen to allow servers to clear player inventories when regenerating islands.
> Added regenInventoryClear

- src/main/java/com/iridium/iridiumskyblock/configs/Configuration.java
- src/main/java/com/iridium/iridiumskyblock/listeners/PlayerInteractListener.java
- added endPortalPick configuration setting to allow the end portal frames to be picked up and placed again, as they are indestructable blocks (right click with wooden pickaxe, consumes pickaxe)
- restructured PlayerInteractListener to accommodate multiple listening targets
> Added endPortalPick setting

- src/main/java/com/iridium/iridiumskyblock/configs/Configuration.java
- src/main/java/com/iridium/iridiumskyblock/listeners/BlockFormListener.java
added `netherOnlyGenerator` config option and a check to `BlockFormListener` to determine whether to activate the basalt generator in the overworld & end or be nether exclusive
> netherOnlyGenerator

- src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
added `backupConfigs` to copy all current config files (and database) to a backup folder on plugin load / reload (thank you faun for helping me fix this mess)
> Added backupConfigs

- src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
- src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
used NBTAPI to edit level.dat values and prevent the dragon or bedrock portal from spawning because im cool like that (should fix 749)
> killed the dragon

- src/main/java/com/iridium/iridiumskyblock/commands/RegenCommand.java
- src/main/java/com/iridium/iridiumskyblock/configs/Configuration.java
- src/main/java/com/iridium/iridiumskyblock/configs/Messages.java
- src/main/java/com/iridium/iridiumskyblock/configs/Schematics.java
- src/main/java/com/iridium/iridiumskyblock/managers/SchematicManager.java
- added `payPerRegen` setting to allow servers to charge players to regenerate their island
- includes a message sent to players of the island when purchased with `%schematic% placeholder to add schematic name to message
- missing schematic lore
> Added payPerRegen setting

- src/main/java/com/iridium/iridiumskyblock/configs/Configuration.java
- src/main/java/com/iridium/iridiumskyblock/listeners/PlayerJoinListener.java
> Actually Island Create on Join

- src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
- src/main/java/com/iridium/iridiumskyblock/configs/Schematics.java
- src/main/java/com/iridium/iridiumskyblock/listeners/PlayerPortalListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/PortalCreateListener.java
Fix #779 
It works well.
Also fixed player not being in the correct location after teleported. (Old behavior players will be teleported inside the block)
`setCanCreatePortal` may be incompatible with 1.15-, but it seems possible to abandon 1.15-?
> Prevent obsidian platform generate in The End

- src/main/java/com/iridium/iridiumskyblock/api/IridiumSkyblockAPI.java
- src/main/java/com/iridium/iridiumskyblock/database/Island.java
Fixes the static block initializing in API and adds missing getOwner/getMembers
> Fix Api bug and add standard getOwner/getMembers

- build.gradle.kts
- src/main/java/com/iridium/iridiumskyblock/placeholders/IslandPlaceholderBuilder.java
- modified the fetch for online and offline members to run a single stream to create both lists
- added ``island_visitors`` and ``island_visitors_amount`` placeholders to get the list of player names visiting an island and the amount of current visitors to said island
- added ``island_booster`` and ``island_upgrade`` placeholders, to get whether they're active, the level of the enhancement, and the time remaining
> added more placeholders

- src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
- src/main/java/com/iridium/iridiumskyblock/configs/Generators.java
- src/main/java/com/iridium/iridiumskyblock/generators/FlatGenerator.java
- src/main/java/com/iridium/iridiumskyblock/managers/GeneratorType.java
- also added some logging about the generator type to ensure that server admins know what the correct enum values are
> Added flatlands generator

- src/main/java/com/iridium/iridiumskyblock/listeners/PlayerInteractListener.java
- reimplemented click to deposit so that the default lore tooltip actually makes sense
- required removing the ignoreCancelled flag as right clicking in air automatically sets the event as cancelled apparently
> you can click the crystal now

- .github/ISSUE_TEMPLATE/bug_report.yml
If we don't want feature requests as issues, there's no need to clutter the title with this, especially given there's also a bug label
> Remove default title of bug report issue template

- build.gradle.kts
The order is based on the combined number of commits on GitHub in the three related projects (which includes v3 commits, but part of that was copied into v4).  boiscljo wants to be excluded. We can reorder the list if we want it to focus on v4 contributions.
> Add major contributors to plugin.yml as authors

- build.gradle.kts
This appears to be some sort of "convention" to make it easier to update plugins from the /plugins list. I think it makes sense to add the SpigotMC link there
> Add SpigotMC URL to plugin.yml

- src/main/java/com/iridium/iridiumskyblock/configs/Missions.java
Updated the incorrect PotionBrewer Reward message that was placed in the Mine Logs one-time missions section.
> Updated Incorrect Reward Message
