- src/main/java/com/iridium/iridiumskyblock/commands/AboutCommand.java
- src/main/java/com/iridium/iridiumskyblock/commands/CommandManager.java
- src/main/java/com/iridium/iridiumskyblock/commands/KickCommand.java
- src/main/java/com/iridium/iridiumskyblock/commands/PrivateCommand.java
- src/main/java/com/iridium/iridiumskyblock/commands/PublicCommand.java
- src/main/java/com/iridium/iridiumskyblock/commands/VisitCommand.java
- src/main/java/com/iridium/iridiumskyblock/configs/Configuration.java
- src/main/java/com/iridium/iridiumskyblock/configs/Inventories.java
- src/main/java/com/iridium/iridiumskyblock/configs/Messages.java
- src/main/java/com/iridium/iridiumskyblock/database/Island.java
- src/main/java/com/iridium/iridiumskyblock/gui/VisitGUI.java
- src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
visit gui it was silly,  that should make by @PeachesMLG
> Added Visit, Public and Private Commands

- src/main/java/com/iridium/iridiumskyblock/Item.java
- src/main/java/com/iridium/iridiumskyblock/PlaceholderBuilder.java
- src/main/java/com/iridium/iridiumskyblock/gui/IslandTopGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/MembersGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/VisitGUI.java
Added PlaceholderBuilder to provide more continuity between placeholders
> Added PlaceholderBuilder

- src/main/java/com/iridium/iridiumskyblock/managers/DatabaseManager.java
Fixes #42, at least the connection issue
> Fix the sql connection string

- src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
- src/main/java/com/iridium/iridiumskyblock/commands/InviteCommand.java
- src/main/java/com/iridium/iridiumskyblock/commands/JoinCommand.java
- src/main/java/com/iridium/iridiumskyblock/commands/SaveSchematicCommand.java
- src/main/java/com/iridium/iridiumskyblock/commands/UnInviteCommand.java
- src/main/java/com/iridium/iridiumskyblock/database/Island.java
- src/main/java/com/iridium/iridiumskyblock/gui/VisitGUI.java
- src/main/java/com/iridium/iridiumskyblock/listeners/BlockPlaceListener.java
- src/main/java/com/iridium/iridiumskyblock/managers/DatabaseManager.java
- src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
- src/main/java/com/iridium/iridiumskyblock/managers/SchematicManager.java
- src/main/java/com/iridium/iridiumskyblock/managers/TableManager.java
- src/main/java/com/iridium/iridiumskyblock/managers/UserManager.java
Cleaning up IslandManager and remove duplicate Code
> Clean up IslandManager

- plugin/src/main/java/com/iridium/iridiumskyblock/commands/InviteCommand.java
- plugin/src/main/java/com/iridium/iridiumskyblock/commands/TrustCommand.java
- plugin/src/main/java/com/iridium/iridiumskyblock/commands/UnTrustCommand.java
- plugin/src/main/java/com/iridium/iridiumskyblock/database/IslandBank.java
- plugin/src/main/java/com/iridium/iridiumskyblock/database/IslandBlocks.java
- plugin/src/main/java/com/iridium/iridiumskyblock/database/IslandData.java
- plugin/src/main/java/com/iridium/iridiumskyblock/database/IslandInvite.java
- plugin/src/main/java/com/iridium/iridiumskyblock/database/IslandMission.java
- plugin/src/main/java/com/iridium/iridiumskyblock/database/IslandPermission.java
- plugin/src/main/java/com/iridium/iridiumskyblock/database/IslandReward.java
- plugin/src/main/java/com/iridium/iridiumskyblock/database/IslandTrusted.java
- plugin/src/main/java/com/iridium/iridiumskyblock/database/IslandUpgrade.java
- plugin/src/main/java/com/iridium/iridiumskyblock/gui/InvitesGUI.java
- plugin/src/main/java/com/iridium/iridiumskyblock/gui/TrustedGUI.java
- plugin/src/main/java/com/iridium/iridiumskyblock/listeners/BlockPlaceListener.java
- plugin/src/main/java/com/iridium/iridiumskyblock/managers/DatabaseManager.java
- plugin/src/main/java/com/iridium/iridiumskyblock/managers/ForeignIslandTableManager.java
- plugin/src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
- plugin/src/main/java/com/iridium/iridiumskyblock/managers/IslandTableManager.java
- plugin/src/main/java/com/iridium/iridiumskyblock/managers/SchematicManager.java
- plugin/src/main/java/com/iridium/iridiumskyblock/managers/UserManager.java
Implemented BinarySearch for speeds
> Binary search

- .github/workflows/gradle.yml
Now uploads artifacts and tests the code
> Improve the Github Actions workflow

- plugin/src/main/java/com/iridium/iridiumskyblock/configs/Configuration.java
- plugin/src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
i didn't separate delete and regen, thinking they can be same
> Clear Inventories

- src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
- src/main/java/com/iridium/iridiumskyblock/shop/ShopManager.java
> Fix reload not affecting shop categories

- src/main/java/com/iridium/iridiumskyblock/placeholders/ClipPlaceholderAPI.java
> Fix PAPI reload issues

- build.gradle.kts
- src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
- src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
- src/main/java/com/iridium/iridiumskyblock/shop/ShopManager.java
~~This is only a draft at the moment - it compiles, but won't work on a server.~~
The following things have to be done:
> 1.17 support

- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
> Further improve the Gradle build process

- src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
- src/main/java/com/iridium/iridiumskyblock/listeners/BlockFormListener.java
- src/main/java/com/iridium/iridiumskyblock/utils/RandomAccessList.java
My attempt at optimizing and cleaning up the generator. Alternative to #154
> Cleanup & Optimise the ore generation, Add stone generators

- src/main/java/com/iridium/iridiumskyblock/commands/ChatCommand.java
- src/main/java/com/iridium/iridiumskyblock/configs/Messages.java
Allow online island members to talk privately
> Add /is chat

- src/main/java/com/iridium/iridiumskyblock/configs/Missions.java
> Fix item of cactus quest

- build.gradle.kts
- src/main/java/com/iridium/iridiumskyblock/configs/inventories/BlockValuesInventoryConfig.java
- src/main/java/com/iridium/iridiumskyblock/configs/inventories/ConfirmationInventoryConfig.java
- src/main/java/com/iridium/iridiumskyblock/configs/inventories/InventoryConfig.java
- src/main/java/com/iridium/iridiumskyblock/configs/inventories/IslandRanksInventoryConfig.java
- src/main/java/com/iridium/iridiumskyblock/configs/inventories/IslandTopInventoryConfig.java
- src/main/java/com/iridium/iridiumskyblock/configs/inventories/LogInventoryConfig.java
- src/main/java/com/iridium/iridiumskyblock/configs/inventories/SingleItemGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/BankGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/BoostersGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/ConfirmationGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/GUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/InventoryConfigGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/InvitesGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/IslandRanksGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/IslandTopGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/LogsGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/MembersGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/MissionsGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/PermissionsGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/RewardsGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/SchematicGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/ShopCategoryGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/ShopOverviewGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/TrustedGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/UpgradesGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/VisitGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/WarpsGUI.java
As an alternative to https://github.com/Iridium-Development/IridiumSkyblock/pull/191
> Made plugin get head textures async

- src/main/java/com/iridium/iridiumskyblock/commands/Command.java
- src/main/java/com/iridium/iridiumskyblock/commands/DeleteWarpCommand.java
- src/main/java/com/iridium/iridiumskyblock/commands/DemoteCommand.java
- src/main/java/com/iridium/iridiumskyblock/commands/DepositCommand.java
- src/main/java/com/iridium/iridiumskyblock/commands/EditWarpCommand.java
- src/main/java/com/iridium/iridiumskyblock/commands/FlyCommand.java
- src/main/java/com/iridium/iridiumskyblock/commands/JoinCommand.java
- src/main/java/com/iridium/iridiumskyblock/commands/KickCommand.java
- src/main/java/com/iridium/iridiumskyblock/commands/PromoteCommand.java
- src/main/java/com/iridium/iridiumskyblock/commands/SetWarpCommand.java
- src/main/java/com/iridium/iridiumskyblock/commands/UnInviteCommand.java
- src/main/java/com/iridium/iridiumskyblock/commands/UnTrustCommand.java
- src/main/java/com/iridium/iridiumskyblock/commands/WarpsCommand.java
- src/main/java/com/iridium/iridiumskyblock/commands/WithdrawCommand.java
- src/main/java/com/iridium/iridiumskyblock/commands/subcommands/BankGive.java
- src/main/java/com/iridium/iridiumskyblock/commands/subcommands/BankRemove.java
- src/main/java/com/iridium/iridiumskyblock/commands/subcommands/BankSet.java
- src/main/java/com/iridium/iridiumskyblock/configs/Messages.java
> Fix warp messages & Fix ArrayIndexOutOfBoundsException

- src/main/java/com/iridium/iridiumskyblock/configs/Missions.java
> Fix mission requirements

- src/main/java/com/iridium/iridiumskyblock/managers/tablemanagers/ForeignIslandTableManager.java
> Fix ForeignIslandTableManager NullPointerException

- src/main/java/com/iridium/iridiumskyblock/configs/inventories/NoItemGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/BankGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/BiomeGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/BoostersGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/ConfirmationGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/GUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/InventoryConfigGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/InvitesGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/IslandCreateGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/IslandRanksGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/IslandTopGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/LogsGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/MembersGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/MissionsGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/PermissionsGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/RewardsGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/SchematicGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/ShopOverviewGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/TrustedGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/UpgradesGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/VisitGUI.java
- src/main/java/com/iridium/iridiumskyblock/gui/WarpsGUI.java
They are already used in the warps GUI but not supported
> Add support for inventory title placeholders

- src/main/java/com/iridium/iridiumskyblock/listeners/InventoryClickListener.java
Prevents player inventory clicks from clicking guis
> Fix inventory clicks activating guis

- src/main/java/com/iridium/iridiumskyblock/api/UserChatToggleEvent.java
- src/main/java/com/iridium/iridiumskyblock/commands/ChatCommand.java
- src/main/java/com/iridium/iridiumskyblock/listeners/PlayerChatListener.java
Add User Island chat toggle event (from #suggestions)
Add placeholders to island chat
> Placeholder support to island chat

- src/main/java/com/iridium/iridiumskyblock/gui/ShopCategoryGUI.java
ignore selling with drop and middle buttons
> Make shop sells only with right click

- src/main/java/com/iridium/iridiumskyblock/listeners/BlockFormListener.java
- src/main/java/com/iridium/iridiumskyblock/utils/RandomAccessList.java
> Fix ore generator NullPointerException

- src/main/java/com/iridium/iridiumskyblock/listeners/PlayerInteractListener.java
> Fix entity spawning on foreign islands

- src/main/java/com/iridium/iridiumskyblock/api/IridiumSkyblockAPI.java
- src/main/java/com/iridium/iridiumskyblock/listeners/BlockBreakListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/BlockFormListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/BlockGrowListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/BlockPistonListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/BlockPlaceListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/EnchantItemListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/EntityDamageListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/EntityDeathListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/ItemCraftListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/PlayerFishListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/PlayerInteractListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/PlayerMoveListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/PlayerRespawnListener.java
- src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
Fixes issues with missing world checks, e.g. for missions.
Also fixes border issues on respawn.
> Fix world issues

- src/main/java/com/iridium/iridiumskyblock/listeners/BlockBreakListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/BlockExplodeListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/BlockFormListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/BlockPistonListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/BlockPlaceListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/BucketListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/EntityDamageListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/EntityExplodeListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/EntityPickupItemListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/EntitySpawnListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/InventoryClickListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/PlayerDropItemListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/PlayerInteractListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/PlayerMoveListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/PlayerPortalListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/PlayerTeleportListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/SpawnerSpawnListener.java
fix #281 and some performance by ignoring cancelled events
> Fix events

- src/main/java/com/iridium/iridiumskyblock/database/types/XMaterialType.java
- src/main/java/com/iridium/iridiumskyblock/managers/DatabaseManager.java
Fixes #298 and other future XMaterial changes
> Fix database XMaterial loading

- src/main/java/com/iridium/iridiumskyblock/listeners/PlayerMoveListener.java
Fixes problem with void teleport.
> Fix void teleport

- src/main/java/com/iridium/iridiumskyblock/commands/BlockValueCommand.java
- src/main/java/com/iridium/iridiumskyblock/configs/BlockValues.java
- src/main/java/com/iridium/iridiumskyblock/database/Island.java
- src/main/java/com/iridium/iridiumskyblock/gui/BlockValueGUI.java
> Make blockvaluesgui pageable+slotable

- src/main/java/com/iridium/iridiumskyblock/listeners/EntityDamageListener.java
Fixes #318. Not the perfect solution but I think it's good enough
> Fix projectile message spam

- src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
- src/main/java/com/iridium/iridiumskyblock/configs/Configuration.java
- src/main/java/com/iridium/iridiumskyblock/configs/Placeholders.java
- src/main/java/com/iridium/iridiumskyblock/gui/UpgradesGUI.java
- src/main/java/com/iridium/iridiumskyblock/placeholders/ClipPlaceholderAPI.java
- src/main/java/com/iridium/iridiumskyblock/placeholders/MVDWPlaceholderAPI.java
- src/main/java/com/iridium/iridiumskyblock/placeholders/Placeholders.java
This adds the ability for people to customize the default values for each individual placeholders instead of a global one.
This will use placeholders.yml
> Per-Placeholder Default Values

- src/main/java/com/iridium/iridiumskyblock/configs/Configuration.java
- src/main/java/com/iridium/iridiumskyblock/listeners/PlayerJoinQuitListener.java
please add this, it took me a whole 30 seconds to create this feature and id really appreciate it if you didnt make me waste a whole 30s on making this change
also it can be kinda annoying so to save the whining from people in #support, just merge it, we'd all be better off
> add option to disable patreon message

- src/main/java/com/iridium/iridiumskyblock/DataConverter.java
- src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
- src/main/java/com/iridium/iridiumskyblock/database/IslandBank.java
- src/main/java/com/iridium/iridiumskyblock/database/IslandBlocks.java
- src/main/java/com/iridium/iridiumskyblock/database/IslandBooster.java
- src/main/java/com/iridium/iridiumskyblock/database/IslandData.java
- src/main/java/com/iridium/iridiumskyblock/database/IslandMission.java
- src/main/java/com/iridium/iridiumskyblock/database/IslandSpawners.java
- src/main/java/com/iridium/iridiumskyblock/database/IslandUpgrade.java
- src/main/java/com/iridium/iridiumskyblock/managers/tablemanagers/ForeignIslandTableManager.java
Not sure if I like this or not since the code is 99% the same for each method, feels like I can do this with a loop or something but im too dum to figure it out
> Delete duplicates from Database

- src/main/java/com/iridium/iridiumskyblock/configs/Configuration.java
- src/main/java/com/iridium/iridiumskyblock/utils/PlayerUtils.java
Finally did push on intellij lol
> Make changeable spawn world

- src/main/java/com/iridium/iridiumskyblock/managers/tablemanagers/ForeignIslandTableManager.java
This might give an infinite loop if its null
> Fixed an infinite loop

- src/main/java/com/iridium/iridiumskyblock/commands/PrivateCommand.java
Reverts Iridium-Development/IridiumSkyblock#341
> Revert "Anti-Island Member Kick"

- src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
- src/main/java/com/iridium/iridiumskyblock/PermissionType.java
- src/main/java/com/iridium/iridiumskyblock/configs/Messages.java
- src/main/java/com/iridium/iridiumskyblock/configs/Permissions.java
- src/main/java/com/iridium/iridiumskyblock/listeners/PlayerPortalListener.java
Added island permission for members to access portals on a player's island.
> Add Island Portal Permission

- src/main/java/com/iridium/iridiumskyblock/listeners/PlayerInteractListener.java
> Add cooldown for interaction messages

- src/main/java/com/iridium/iridiumskyblock/configs/Placeholders.java
- src/main/java/com/iridium/iridiumskyblock/placeholders/Placeholders.java
have I tested this? no, Will I? no
i wrote it so it has to work first time /s :)
> Island Biome Placeholders

- src/main/java/com/iridium/iridiumskyblock/managers/DatabaseManager.java
- src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
i just sorted tablemanagers as alphabetically
> Clear database entries with island deletion

- build.gradle.kts
- src/main/java/com/iridium/iridiumskyblock/commands/BankCommand.java
- src/main/java/com/iridium/iridiumskyblock/commands/Command.java
- src/main/java/com/iridium/iridiumskyblock/commands/CommandManager.java
- src/main/java/com/iridium/iridiumskyblock/commands/bank/GiveCommand.java
- src/main/java/com/iridium/iridiumskyblock/commands/bank/RemoveCommand.java
- src/main/java/com/iridium/iridiumskyblock/commands/bank/SetCommand.java
- src/main/java/com/iridium/iridiumskyblock/configs/Commands.java
I also shortened the code that registers all commands. I know that @PeachesMLG didn't want this last time but I managed to find a solution without using a third-party library that is in my opinion way better than the manual registration. I can revert that part if it's still not wanted.
> Add proper subcommand system, Cleanup CommandManager code

- src/main/java/com/iridium/iridiumskyblock/shop/ShopManager.java
- src/main/java/com/iridium/iridiumskyblock/utils/PlayerUtils.java
Fixed the bug reported in #402
> Fix Withdrawing if inventory is full.

- src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
Fixed #372 
Thank you intellij i've edited this on web cause intellij doesn't commits changes (my intellij broken)
> Send chunks after biomes changed

- build.gradle.kts
- src/main/java/com/iridium/iridiumskyblock/configs/Schematics.java
- src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
- src/main/java/com/iridium/iridiumskyblock/managers/SchematicManager.java
> Change height schematic Island

- src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
- src/main/java/com/iridium/iridiumskyblock/configs/Configuration.java
- src/main/java/com/iridium/iridiumskyblock/configs/Messages.java
- src/main/java/com/iridium/iridiumskyblock/listeners/EntityDamageListener.java
- src/main/java/com/iridium/iridiumskyblock/listeners/EntityTargetListener.java
Add Island Damage setting 
Add Pvp settings
Add option to disabling mob targeting to visitors
Fixed issues with sending mobHurt message when a visitor attacked to an island member
Ordered listener registrations as Alphabeticly
> Add new stuffs

- src/main/java/com/iridium/iridiumskyblock/configs/Placeholders.java
- src/main/java/com/iridium/iridiumskyblock/placeholders/Placeholders.java
New placeholders containing the names of all members, visitors, and players on an island as well as the number of visitors and players.
This was requested by a user.
> Add more placeholders

- src/main/java/com/iridium/iridiumskyblock/commands/HelpCommand.java
- src/main/java/com/iridium/iridiumskyblock/commands/InviteCommand.java
- src/main/java/com/iridium/iridiumskyblock/configs/Messages.java
> Add click to join button to invite command

- src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
- src/main/java/com/iridium/iridiumskyblock/configs/Schematics.java
Sorry i'll merge it instantly, i forgot making it on master its just a simple fix
> fix for schematic heights

- .github/workflows/gradle.yml
Add :
- Cache Gradle
- Dont build if contains: [ci-skip]
- Update setup-java to v2
> [ci-skip] Update Workflow

- build.gradle.kts
This will enable the `<#HEX>` RGB color syntax for configs
> Bump IridiumCore to 1.3.2

- src/main/java/com/iridium/iridiumskyblock/managers/SchematicManager.java
AsyncWorldEdit can too paste with Async Task
> Add AsyncWorldEdit

- src/main/java/com/iridium/iridiumskyblock/listeners/EntitySpawnListener.java
> Fix mob spawn setting blocking all entities

- src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
> Fix island ban check

- src/main/java/com/iridium/iridiumskyblock/listeners/PlayerFishListener.java
> Fix entity hooking triggering mission

- src/main/java/com/iridium/iridiumskyblock/commands/RecalculateCommand.java
- src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
> Optimization: Use Async Task Recalculate Command

- build.gradle.kts
Upgrading ormlite implementation
> Migrate to a safe OrmLite version

- src/main/java/com/iridium/iridiumskyblock/api/IridiumSkyblockReloadEvent.java
- src/main/java/com/iridium/iridiumskyblock/api/IslandCreateEvent.java
- src/main/java/com/iridium/iridiumskyblock/api/IslandDeleteEvent.java
- src/main/java/com/iridium/iridiumskyblock/api/IslandRegenEvent.java
- src/main/java/com/iridium/iridiumskyblock/api/IslandRenameEvent.java
- src/main/java/com/iridium/iridiumskyblock/api/IslandSettingChangeEvent.java
- src/main/java/com/iridium/iridiumskyblock/api/ShopPurchaseEvent.java
- src/main/java/com/iridium/iridiumskyblock/api/ShopSellEvent.java
- src/main/java/com/iridium/iridiumskyblock/api/UserChatToggleEvent.java
- src/main/java/com/iridium/iridiumskyblock/api/UserDemoteEvent.java
- src/main/java/com/iridium/iridiumskyblock/api/UserJoinEvent.java
- src/main/java/com/iridium/iridiumskyblock/api/UserKickEvent.java
- src/main/java/com/iridium/iridiumskyblock/api/UserLeaveEvent.java
- src/main/java/com/iridium/iridiumskyblock/api/UserPromoteEvent.java
- src/main/java/com/iridium/iridiumskyblock/commands/RenameCommand.java
- src/main/java/com/iridium/iridiumskyblock/gui/IslandSettingsGUI.java
- src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
- src/main/java/com/iridium/iridiumskyblock/shop/ShopManager.java
- Add documentation & @NotNull annotations
- Add ShopPurchaseEvent
- Add ShopSellEvent
- Add IslandRenameEvent
- Implement & Extend IslandSettingChangeEvent
- Enhanced IslandCreateEvent
> Improve event api

- src/main/java/com/iridium/iridiumskyblock/listeners/BlockBreakListener.java
Fixed a bug in which if we break crops in missions, it does not check if it is mature.
> Fixed Bug Crops Mine Mission

- src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
Fixes https://github.com/Iridium-Development/IridiumSkyblock/issues/499
> Fixed Issues with Daily Island Missions

- src/main/java/com/iridium/iridiumskyblock/utils/PlayerUtils.java
Fix Possible NullPointerException With Essentials
> Fix Possible NullPointerException

- src/main/java/com/iridium/iridiumskyblock/DatabaseObject.java
- src/main/java/com/iridium/iridiumskyblock/database/Island.java
- src/main/java/com/iridium/iridiumskyblock/database/IslandBank.java
- src/main/java/com/iridium/iridiumskyblock/database/IslandBlocks.java
- src/main/java/com/iridium/iridiumskyblock/database/IslandBooster.java
- src/main/java/com/iridium/iridiumskyblock/database/IslandData.java
- src/main/java/com/iridium/iridiumskyblock/database/IslandMission.java
- src/main/java/com/iridium/iridiumskyblock/database/IslandPermission.java
- src/main/java/com/iridium/iridiumskyblock/database/IslandSetting.java
- src/main/java/com/iridium/iridiumskyblock/database/IslandSpawners.java
- src/main/java/com/iridium/iridiumskyblock/database/IslandUpgrade.java
- src/main/java/com/iridium/iridiumskyblock/database/IslandWarp.java
- src/main/java/com/iridium/iridiumskyblock/database/User.java
- src/main/java/com/iridium/iridiumskyblock/managers/tablemanagers/TableManager.java
Before:
After:
Clear difference in speed, just not sure I like the code for this, its very repetitive and if we forget to call setChanged somewhere then it could cause data loss
> Optimised Saving Data

- src/main/java/com/iridium/iridiumskyblock/placeholders/Placeholders.java
> Fix top placeholders starting at the second place

- build.gradle.kts
- src/main/java/com/iridium/iridiumskyblock/configs/Configuration.java
- src/main/java/com/iridium/iridiumskyblock/database/Island.java
Thoughts on how we do the getExperienceRequired method?
We could just do a brute force approach but that seems dum
> Made IslandLevelEquation configurable

- src/main/java/com/iridium/iridiumskyblock/commands/AboutCommand.java
@DoctaEnkoda created a fair amount of pretty decent PRs
> Add DoctaEnkoda to the list of contributors

- src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
I found the bug by putting a catch on IslandManager#recalculateIsland(Island)
> Fix issue Async task on entities

- src/main/java/com/iridium/iridiumskyblock/commands/HomeCommand.java
- src/main/java/com/iridium/iridiumskyblock/commands/home/CurrentOffsetCommand.java
- src/main/java/com/iridium/iridiumskyblock/configs/Messages.java
It would probably be better to have it as a subcommand for the admin command, but I believe that this is a good (temporary) solution.
> Add CurrentOffset command

- src/main/java/com/iridium/iridiumskyblock/commands/Command.java
- src/main/java/com/iridium/iridiumskyblock/commands/CommandManager.java
Tested this PR too. Seriously, what's wrong with me?
> Fix subcommands appearing in tabcompletion without permissions

- src/main/java/com/iridium/iridiumskyblock/listeners/PlayerInteractListener.java
I just tested it but forgot what the issue is. You either deposit two crystals when you do or don't click on a block. There is an explanation in the code. Spigot is dum
> Fix right-clicking depositing two crystals at once

- src/main/java/com/iridium/iridiumskyblock/listeners/PlayerInteractListener.java
> Optimize something

- src/main/java/com/iridium/iridiumskyblock/generators/OceanGenerator.java
> Fix 1.18 ocean generation

- src/main/java/com/iridium/iridiumskyblock/configs/BankItems.java
> Increase default money withdrawal amount

- src/main/java/com/iridium/iridiumskyblock/api/IridiumSkyblockAPI.java
Improves documentation & adds Jetbrains annotations everywhere
> Improve IridiumSkyblockAPI class

- build.gradle.kts
- src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
- src/main/java/com/iridium/iridiumskyblock/bank/MoneyBankItem.java
- src/main/java/com/iridium/iridiumskyblock/generators/OceanGenerator.java
- src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
- src/main/java/com/iridium/iridiumskyblock/managers/SchematicManager.java
- src/main/java/com/iridium/iridiumskyblock/placeholders/ClipPlaceholderAPI.java
- src/main/java/com/iridium/iridiumskyblock/placeholders/MVDWPlaceholderAPI.java
- src/main/java/com/iridium/iridiumskyblock/placeholders/Placeholders.java
- src/test/java/com/iridium/iridiumskyblock/commands/BanCommandTest.java
- src/test/java/com/iridium/iridiumskyblock/commands/CreateCommandTest.java
Merging the fork into 3.2.x branch
> 3.2.9 Release code in 3.2.x branch

- build.gradle.kts
- src/main/java/com/iridium/iridiumskyblock/commands/DeleteWarpCommand.java
- src/main/java/com/iridium/iridiumskyblock/commands/RegenCommand.java
- src/main/java/com/iridium/iridiumskyblock/configs/Configuration.java
- src/main/java/com/iridium/iridiumskyblock/database/Island.java
- src/main/java/com/iridium/iridiumskyblock/gui/IslandRegenGUI.java
- src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
- src/main/java/com/iridium/iridiumskyblock/managers/SchematicManager.java
- src/main/java/com/iridium/iridiumskyblock/schematics/FastAsyncWorldEdit.java
- src/main/java/com/iridium/iridiumskyblock/schematics/SchematicAsync.java
- src/main/java/com/iridium/iridiumskyblock/support/WildStackerSupport.java
- src/main/resources/plugin.yml
> 3.2.x - Implemented OM changes

- src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
- src/main/java/com/iridium/iridiumskyblock/configs/Configuration.java
- src/main/java/com/iridium/iridiumskyblock/managers/SchematicManager.java
- src/main/java/com/iridium/iridiumskyblock/schematics/FastAsyncWorldEdit.java
- src/main/java/com/iridium/iridiumskyblock/schematics/Schematic.java
- src/main/java/com/iridium/iridiumskyblock/schematics/SchematicAsync.java
- src/main/java/com/iridium/iridiumskyblock/schematics/WorldEdit.java
Reimplement FAWE support and paster improvement for lag issues from latest 3.2.x versions
> improved paster from 3.2.x

- src/main/java/com/iridium/iridiumskyblock/configs/Configuration.java
- src/main/java/com/iridium/iridiumskyblock/database/Island.java
> made the default island name to be displayed configurable

- build.gradle.kts
- src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
- src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
- src/main/resources/plugin.yml
Requires https://github.com/Iridium-Development/IridiumTeams/pull/63
> Spawner stacker implementation 2

- src/main/java/com/iridium/iridiumskyblock/configs/Configuration.java
- src/main/java/com/iridium/iridiumskyblock/listeners/PlayerRespawnEventListener.java
- src/main/java/com/iridium/iridiumskyblock/utils/PlayerUtils.java
also rewrote the player utils class to use the spawn support from teams, its pretty cool
> you can respawn on your island now, or whatever

- src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java
see https://github.com/Iridium-Development/IridiumCore/pull/99
> Switched from NbtItem to Nbt.modify

- src/main/java/com/iridium/iridiumskyblock/listeners/PlayerInteractListener.java
> Fix permission issue with end portal frames and bucket shenanigans

- src/main/java/com/iridium/iridiumskyblock/IridiumSkyblock.java
> fix: register player respawn event listener
